Modules/Liveo.Platform/Controllers/FeatureAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Liveo.Framework.Model.Service;
using Liveo.Platform.Services;
using Liveo.Platform.ViewModels;
using Orchard.ContentManagement;
using Orchard.DisplayManagement;
using Orchard.DisplayManagement.Shapes;
using Orchard.Localization;
using Orchard.Settings;
using Orchard.UI.Admin;
using Orchard.UI.Navigation;
using Liveo.Platform.Extensions;

namespace Liveo.Platform.Controllers
{
    [ValidateInput(false), Admin]
    public class FeatureAdminController : Controller, IUpdateModel {
        private readonly ILiveoFeatureService _featureService;
        private readonly ISiteService _siteService;
        private dynamic Shape { get; set; }
        private Localizer T { get; set; }

        public FeatureAdminController(ILiveoFeatureService featureService,
            ISiteService siteService,
            IShapeFactory shapeFactory) {
            _featureService = featureService;
            _siteService = siteService;
            Shape = shapeFactory;
        }
        public ActionResult List(PagerParameters pagerParameters, FeatureSearchViewModel search) {
            var featureQuery = _featureService.GetQuery();

            if (!string.IsNullOrWhiteSpace(search.Expression)) {
                string expression = search.Expression.Trim();

                featureQuery = featureQuery.Where(feature => feature.Name.Contains(expression, StringComparison.InvariantCultureIgnoreCase));
            }

            // The pager is used to apply paging on the query and to create a PagerShape
            var pager = new Pager(_siteService.GetSiteSettings(), pagerParameters.Page, pagerParameters.PageSize);

            // Construct a Pager shape
            var pagerShape = Shape.Pager(pager).TotalItemCount(featureQuery.Count());

            // Create the viewmodel
            var model = new FeatureListViewModel(featureQuery.ToList(), search, pagerShape);
            return View(model);
        }

        public new bool TryUpdateModel<TModel>(TModel model, string prefix, string[] includeProperties, string[] excludeProperties) where TModel : class
        {
            return base.TryUpdateModel(model, prefix, includeProperties, excludeProperties);
        }

        public void AddModelError(string key, LocalizedString errorMessage)
        {
            ModelState.AddModelError(key, errorMessage.Text);
        }
    }
}

Modules/Liveo.Platform/Views/FeatureAdmin/List.cshtml
@model Liveo.Platform.ViewModels.FeatureListViewModel
@{
    Script.Require("ShapesBase");
    Layout.Title = T("Features").ToString();
}

@using(Html.BeginForm("List", "FeatureAdmin", FormMethod.Get)) {
    <fieldset class="bulk-actions">
        <label for="search">@T("Search:")</label>
        @Html.TextBoxFor(m => m.Search.Expression)
        <button type="submit">@T("Search")</button>
        <a href="@Url.Action("List")">@T("Clear")</a>
    </fieldset>
}
<fieldset>
    <table class="items" summary="@T("All features in the application")">
        <colgroup>
            <col id="Col1" />
            <col id="Col2" />
            <col id="Col3" />
            <col id="Col4" />
        </colgroup>
        <thead>
            <tr>
                <th scope="col">&nbsp;&darr;</th>
                <th scope="col">@T("Name")</th>
                <th scope="col">@T("RelativeUrl")</th>
                <th scope="col">@T("Actions")</th>
            </tr>
        </thead>
        @foreach (var customer in Model.Features) {
        <tr>
            <td>@customer.Id</td>
            <td>@customer.Name</td>
            <td>@customer.RelativeUrl</td>
            <td>
                <div>
                    <a href="@Url.Action("Edit", new {customer.Id})" title="@T("Edit")">@T("Edit")</a>@T(" | ")
                    <a href="@Url.Action("List", "FeatureAdmin", new {customerId = customer.Id})" title="@T("Addresses")">@T("Addresses")</a>@T(" | ")
                    <a href="@Url.Action("Delete", new {customer.Id, returnUrl = Request.Url.PathAndQuery})">@T("Delete")</a>
                </div>
            </td>
        </tr>
        } 
    </table>
    @Display(Model.Pager)
</fieldset>